services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_records_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_net
    depends_on:
      - postgres
      - redis

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: customer_records_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:delegated
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel_net
    depends_on:
      - app

  # PostgreSQL Service
  postgres:
    image: postgres:16-alpine
    container_name: customer_records_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_net

  # Redis Service
  redis:
    image: redis:alpine
    container_name: customer_records_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local